#!/bin/bash

# Activate macros and colors
#ff0000 = red
#ff00ff = purple
#0000ff = blue
#00ff00 = green
#00ffff = cyan trying 66ffff:1-8
sleep 1.7
sudo apexctl
sleep 1.5
sudo apexctl colors \
-s ff0000:8 \
-n ff00ff:8 \
-w 0000ff:8 \
-e 00ffff:8 \
-l 00ff00:8

exit

