#!/bin/bash

function log_info {
    echo "$(tput setaf 4)$1$(tput sgr0)" >&2
}
function log_warn {
    echo "$(tput setaf 3)$1$(tput sgr0)" >&2
}
function log_error {
    echo "$(tput setaf 1)ERROR:$(tput sgr0) $1" >&2
}


function display_help {
cat <<EOS
Usage: midiplayer [options]  <args> <file>

  midiplayer magic    <file.mid> Magic        Soundfont
  midiplayer fluidgm  <file.mid> Fluid-GM     Soundfont
  midiplayer fluidgs  <file.mid> Fluid-GS     Soundfont
  midiplayer general  <file.mid> General      Soundfont
  midiplayer timidity <file.mid> Timidity     Soundfont
  midiplayer arachno  <file.mid> Arachno      Soundfont
  midiplayer chorium  <file.mid> Chorium      Soundfont
  midiplayer omega    <file.mid> Omega-GM     Soundfont
  midiplayer princess <file.mid> Princess     Soundfont
  midiplayer 32mb     <file.mid> 32Mb-GM      Soundfont
  midiplayer sf4u     <file.mid> SF4U-GM      Soundfont
  midiplayer hqorch   <file.mid> HQ-Orch      Soundfont
  midiplayer heaven   <file.mid> Heaven       Soundfont
  midiplayer muse     <file.mid> Muse2        Soundfont
  midiplayer sblive   <file.mid> SB Live!     Soundfont
  midiplayer musyng   <file.mid> Musyng       Soundfont
  midiplayer sonatina <file.mid> Sonatina     Soundfont
  midiplayer sc55     <file.mid> SC-55        Soundfont
  midiplayer sc55-alt <file.mid> SC-55(2)     Soundfont
  midiplayer sc88     <file.mid> SC-88        Soundfont
  midiplayer airfont  <file.mid> Airfont      Soundfont
  midiplayer 16.5mb   <file.mid> 16.5MB       Soundfont
  midiplayer evan2    <file.mid> Evanessence2 Soundfont
  midiplayer sonivox  <file.mid> SONiVOX GS   Soundfont
  midiplayer yamXG    <file.mid> Yamaha XG    Soundfont
  midiplayer sf2  <file.sf2>  <file.mid>      Manually

Options:
  -h | --help		Show this screen.
  -v | --verbose 	Display the command to be passed through.
  --dry-run             Display the command without running it.
  
EOS
}

CMD='fluidsynth -a alsa -i'
# Match any [options]
while :
do
	case "$1" in
		-h | --help)
			display_help  # Call your function
			# no shifting needed here, we're done.
			exit 0
			;;
		-v | --verbose)
			verbose=true
			shift
			;;
		--dry-run)
			dry_run=true
			shift
			;;
		-L | --local-sf2)
			local_sf2=true
			shift
			;;
		--) # End of all options
			shift
			break
			;;
		-*)
			log_error "Unknown option: $1"
			break
			;;
		*)  # No more options
			break
			;;
	esac
done
case "$1" in
	    'magic')
	    	shift
		    CMD_ARGS="/usr/share/sounds/sf2/MagicSFver2.sf2 "
		    ;;
	    'fluidgm')
		    shift
	    	CMD_ARGS="/usr/share/sounds/sf2/FluidR3_GM.sf2 "
		    ;;
	    'timidity')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/TimGM6mb.sf2 "
            ;;
	    'fluidgs')
	        shift
	        CMD_ARGS="/usr/share/sounds/sf2/FluidR3_GS.sf2 "
	        ;;
	    'general')
	        shift
	        CMD_ARGS="/usr/share/sounds/sf2/GeneralUserGS_1471.sf2 "
            ;;
        'arachno')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/Arachno.sf2 "
            ;;
        'chorium')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/Chorium.sf2 "
            ;;
        'omega')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/Omega.sf2 "
            ;;
        'princess')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/Princess.sf2 "
            ;;
        '32mb')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/32Mb.sf2 "
            ;;
        'sf4u')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/Sf4UGM.sf2 "
            ;;
        'hqorch')
            shift
            CMD_ARGS="/usr/share/sounds/sf2/HQOrchestra.sf2 "
            ;;
	'heaven')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Heaven.sf2 "
		;;
	'muse')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Musescore2.sf2 "
		;;
	'sonatina')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Sonatina.sf2 "
		;;
	'sc55')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Roland_SC-55.sf2 "
		;;
	'sc88')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Roland_SC-88.sf2 "
		;;
	'sblive')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/8MBSBLive.sf2 "
		;;
	'musyng')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Musyng.sf2 "
		;;
	'sc55-alt')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/ALT_Roland_SC-55.sf2 "
		;;
	'airfont')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/airfont380.sf2 "
		;;
	'16.5mb')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/16.5mb-GM-GS-MT32.sf2 "
		;;
	'evan2')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/Evanessence2.sf2 "
		;;
	'sonivox')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/SONiVOX_GS250.sf2 "
		;;
	'yamXG')
		shift
		CMD_ARGS="/usr/share/sounds/sf2/yamahaXG.sf2 "
		;;
	'sf2')
		shift
		CMD_ARGS="$1"
		;;

	 *)
		    log_error "Unknown command: $1"
		   exit 1
        ;;
	esac

# echo the whole command if verbose is enabled
if [ "$verbose" = true ]; then
	log_info "=> $(tput sgr0)$CMD $CMD_ARGS "$@""
fi

# Call the command
if [ "$dry_run" = true ]; then
	echo "$CMD $CMD_ARGS "$@"" 
else
	$CMD $CMD_ARGS "$@"
fi



exit
